### ISSUE TITLE
PayLoad Type example

### ISSUE THREAD

**Issue by loothood** [wolfenrain/bolt#11]
Hi,

Cloud you add a payload type example, please?
For example, I have a class: 
```
class GameClient {
   double x;
   double y;
   String uuid;
}
```
And I want to broadcast to my clients new class with all my clients:
```
class GameStatus {
   List<GameClient> clients;
}
```

In this case, I have to use payload types from your documentation(fix me if I'm wrong), but I don't understand how to register a payload class after the defining.

**Comment by wolfenrain** [comment]
Payload types are used when your register a `DataObject`: https://github.com/wolfenrain/bolt/blob/main/docs/data-objects.md#registering-a-data-object

In your case you would need to define a payload for `GameStatus` that internally uses another payload type for `GameClient`.

I have been working on a layer on top of Bolt for game netcode that makes this easier for game developers but it isn't in a publishable state, but I can try to get it further if you (or anyone else) is interested

**Comment by loothood** [comment]
`but I can try to get it further if you (or anyone else) is interested`
Yes please, that's interesting to me
